<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderContent extends Model
{
    protected $table = 'order_contents';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function($model){

        });
    }

    public function order(){
        return $this->belongsTo('App\Order');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product(){
        return $this->belongsTo('App\Product');
    }
}
